#!/bin/bash

test_server_stdout=tests/server.stdout

function install_deps {
    pip install -e ".[dev]"
}

function start_server {
    rm -f ${test_server_stdout}
    python tests/m3u8server.py >${test_server_stdout} 2>&1 &
}

function stop_server {
    pkill -9 -f m3u8server.py
    echo "Test server stdout on ${test_server_stdout}"
}

function run {
    py.test -vv --cov-report term-missing --cov openm3u8 tests/
    python tests/test_roundtrip_hashes.py
}

function main {
    install_deps
    start_server
    run
    retval=$?
    stop_server
    return "$retval"
}

if [ -z "$1" ]; then
    main
else
    "$@"
fi
